version = 1

test_patterns = [
    "tests-karma/**",
    "tests-nose/**"
]

exclude_patterns = []

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  additional_builtins = ["_"]
